kind: pipeline
type: docker
name: Project Build and Deploy

steps:    
  - name: Deploy to Docker Hub  
    image: plugins/docker
    settings:
      username:
      from_secret: username
      password:
      from_secret: password
      repo: sijaymm/inventorywebapi
      dockerfile: path/to/Dockerfile
      tags: latest
      auto_tag: true
  


  - name: Deploy to Heroko
    image: heroku/heroku
    commands:
      - heroku login
      - heroku container:login
      - heroku container:push web -a omni-inventory-web-api
      - heroku container:release web -a omni-inventory-web-api

trigger:
  branch:
    include:
      - master
  event:
    include:
      - push
