kind: pipeline
name: Project Build and Deploy

steps:    
- name: docker  
  image: plugins/docker
  settings:
    username: sijaymm
    password: "@@Win4me@@cj1995"
    repo: sijaymm/inventorywebapi
    dockerfile: path/to/Dockerfile
    tags: latest
    bip: false
    experimental: true
    insecure: true
    

trigger:
  branch:
    include:
      - master
  event:
    include:
      - push
