kind: pipeline
type: docker
name: Project Build and Deploy

steps:    
 
  - name: Deploy to Docker Hub  
    image: plugins/docker
    settings:
      username: sijaymm
      password: @@Win4me@@cj1995
    repo: sijaymm/inventorywebapi
    dockerfile: path/to/Dockerfile


  - name: Deploy to Heroko
    image: heroku/heroku
    commands:
      - heroku login
      - heroku container:login
      - heroku container:push web -a omni-inventory-web-api
      - heroku container:release web -a omni-inventory-web-api

trigger:
  branch:
    include:
      - master
  event:
    include:
      - push
